language: java
jdk: openjdk8
before_install:
- chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure: jHIZm5KowDPo8b/5c2WiSbyaPD2xmVC5v2OCdmuFKRJvs1mbxxWzYORCAPw7mvOpdN0UgERe9Rm0JAV1L2OrxpHK3+tuX2toufUMmrydWzEYseqiQoZFbhI9JJ07WkbA5CgqwbmqBIdUHLuK9fD+6ZIfbLc1qtbmuLW6lFjABGNbwrIUpb8TgeuqfnCnK0+CiqiUBBMrI0aBkIX4/oOwCx7RhkU+52QBI8riTReUZAe5EE6ngaRUHRs/hIRKZfIqFUCetyQchqyU13A9Mxklp2ULSBmretTLlYAcN8nqTvQJPaDtmVJqpb7stFQ7BzGUOLE0jnwDQN1ULu28UUHxB/JzQBOW8xcCHje0gJ8mBq6mQHYYOuxUz6YXaTuWMExeEfwLPzAcSFQpJc2S+aBHu3O2QV81p3L6E7Y7/sn1JlaeJ2mdZefwqfo5RojSjgbuisua1aVnpYVcf0QxbEKOCfuAbfRCTM8LMd7yZ/XmwMiwL4bCFTMaPC01pmv6x5w6RlFIZ6ADu5WRffa7kiwFOFOLHHP+trlZp/HVxO/HzRK21VRcMbwrH4vMcwIZjqu0cFGMHESMsRQCQVN2bCwRNkr3j0xiTReWN+jkqIyo0m/p9osMFC3hSwLqwKO1T6wtYX0QMqPR3CHSboyKUCU9MP0XTAcrjyVLhxOqaXSfmhU=
  file: build/libs/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xlr-blazemeter-plugin
notifications:
  slack:
    secure: u6uCBl1kWPMl9YZBP8v+U2+B/QgoTVLXJjE/RbfJOAcqw/VNjt3+niv2uhyReXJLShsDmeJYaKh70mBP+iJcb3LywY6GS0nWMqjHpGFu3xw4XlyXLuEhmuDZ7KY2waxSvOfYxDtmdHwEd8Pl1g2f+/ssthEl5H1dUQulAt3muuKxkK1vhM0bTsZXF/evlXgNReNsU1h8Pz8F0uScWUU0VekEo8e8oTw7JLbx6GYXSX6uhnYzHo9u/N+h+kBSYOGp9XJqfWSQHFPxjOZM0Ol6KFe/LYHYGKQPM3hE0/A6wdVX1F/dx/bQpwZ29izF7BN3p721Ulbsl6kEZ30mht2OHRhlZN5MzSHYDmagzQdQv2QuSMyW6KnUgoYQXDS/WJrlun/uxMUaVrr4RgB0QiN2Ix8S/A3zy3JJMfrhA5brTnuzE1B7pDFVxFJGkX5cJhafLXQbKqNoBVHWs2YzwrdoEZty57zTy8ehQA8LtxY9KwhhnlC7KD9QbfOrP37KZZRJ/hyGmwj67nt48jfKsuhS4OXJmGw6unOv2WkUKicWTlgKBwqaY49hDdi72TAI8Xten9PnwxM28bcXDZV3OGrGXHqu/WBPLmIctfz9qqSxiFmw/RslmxnGszGBiJRP0HZbwicnZlHxgerofWWs2Mjt+e+P1k5xwqeqwNlsUu4vJVA=
